#!/bin/bash

count=$(git diff --cached --name-only | grep "spec" -c)
if [ $count -eq 0 ]; then
  exit 0
fi

status=0
flags=( ':focus' 'focus: true' 'focus => true')
for flag in "${flags[@]}"; do
  git diff --cached --name-only | grep "spec" | xargs grep "$flag" --color -Hni
  if [ $? -eq 0 ]; then  # status code = 0 means lines are found
    status=1
  fi
done

exit $status
