#!/bin/bash

count=$(git diff --cached --name-only | grep ".rb$" -c)
if [ $count -eq 0 ]; then
  exit 0
fi

bundle exec rubocop `git diff HEAD --name-only --diff-filter=MA & git diff master..HEAD --name-only --diff-filter=MA | sort | uniq`
